name: Scheduled healthcheck

on:
    schedule:
      - cron: '0/1 * * * *'

jobs:
  healthcheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://cezar-budeci-pokedex-ce8d59703a06.herokuapp.com/
          max-attempts: 3
          retry-delay: 30s
      - name: send success notification
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
            severity: 'info'
            username: 'Github'
            details: 'Successful healthcheck'
            footer: 'Severity: Info'
            text: 'Successful healthcheck'
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: send failure notification
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
            severity: 'error'
            username: 'Github'
            details: 'Healthcked failed'
            footer: 'Severity: Error'
            text: 'Healthcked failed'
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
