name: Test pipeline

on:
    push:
        branches:
            - master

jobs:
  test_commit_messages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: commit messages
        env:
          COMMIT_MESSAGES_STRING: ${{join(github.event.commits.*.message)}}
        if: ${{ contains(env.COMMIT_MESSAGES_STRING, '#skip')}}
        run: echo "$COMMIT_MESSAGES_STRING"
